# DIRECTIVE
# helpdoc - help documentation system
#
# USAGE
# $(call helpdoc,<target_name>,[<help_text>])
#
# DESCRIPTION
# The "helpdoc" function is used for adding distributed help
# documentation to a build system. When called, the "helpdoc" function
# creates a .PHONY target named "help.<target_name>" which displays the
# provided <help_text>. A user can then run "make help.<target_name>" on
# the command line to view help documentation for <target_name>.
#
# "helpdoc.mk" also adds three standard targets to the build system:
# "help", "help-show-all", and "help-list-all". These targets are
# described in more detail in the TARGETS section below.
#
# ARGUMENTS
# <target_name>
# The name of the target to generate help documentation for. A new
# .PHONY help.<target_name> target is created to display help
# documentation for <target_name>. The help.<target_name> target has no
# dependency relation to <target_name>.
#
# <help_text> [OPTIONAL]
# The text to display when the help.<target_name> target is rebuilt. If
# no <help_text> is provided, the created help.<target_name> target
# displays a message indicating that there is no help text available.
#
# RETURNS
# Empty string.
#
# VARIABLES
# $(__helpdoc_template) [PRIVATE]
# Rule template used for creating help.<target_name> targets.
# __helpdoc_template is a function that is called, and then $(eval)'d to
# create a new help.<target_name> target.
#
# $(__helpdoc_targets) [PRIVATE]
# List of all <target_name>'s registered with the "helpdoc" function.
# This list is used by the help-show-all and help-list-all targets.
#
# $(__helpdoc_loop) [PRIVATE]
# A loop variable used internally by "helpdoc.mk".
#
# TARGETS
# help.<target_name>
# A .PHONY target generated by calling "helpdoc" with <target_name> as
# an argument. Rebuilding the help.<target_name> target displays
# <target_name> and the <help_text> that was originally passed to
# "helpdoc".
#
# help
# Standard target created by "helpdoc.mk". Displays a message
# introducing the standard targets in the help documentation system.
# This target is a candidate for .DEFAULT_GOAL.
#
# help-show-all
# Standard target created by "helpdoc.mk". Displays <help_text> for all
# registered <target_name> targets by rebuilding each help.<target_name>
# target.
#
# help-list-all
# Standard target created by "helpdoc.mk". Displays a list of all
# <target_name> targets registered with the "helpdoc" function. Used for
# discovering available targets.

ifndef helpdoc

# Rule template for help.<target_name> targets created with "helpdoc"
# function
define __helpdoc_template
.PHONY: help.$(1)
help.$(1):
	$$(info $(1):)
	$(if $(2),$$(info $(2)),$$(info (no help text)))
	$$(info )
	@true
endef

# "helpdoc" function definition
helpdoc = $(if \
  $(eval $(call __helpdoc_template,$(1),$(2))) \
  $(eval __helpdoc_targets := $(sort $(__helpdoc_targets) $(1))) \
,,)

# "help" target rule
.PHONY: help
$(call helpdoc,help,Show message introducing the help documentation system)
help:
	$(info Help Documentation)
	$(info ==================)
	$(info )
	$(info make help-show-all:)
	$(info Show help for all targets with available help documentation)
	$(info )
	$(info make help-list-all:)
	$(info List all targets with available help documentation)
	$(info )
	$(info make help.<target_name>:)
	$(info Show help for <target_name>)
	$(info )
	$(info make help:)
	$(info Show message introducing the help documentation system (this message))
	$(info )
	@true

# "help-show-all" target rule
.PHONY: help-show-all
$(call helpdoc,help-show-all,Show help for all targets with available help documentation)
help-show-all:
	@$(MAKE) --no-print-directory $(addprefix help.,$(__helpdoc_targets))

# "help-list-all" target rule
.PHONY: help-list-all
$(call helpdoc,help-list-all,List all targets with available help documentation)
help-list-all:
	$(foreach __helpdoc_loop,$(__helpdoc_targets),$(info $(__helpdoc_loop)))
	@true
endif
